// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lesson9.proto

package com.cnebrera.uc3.tech.lesson9.proto;

public final class Lesson9 {
    private Lesson9() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface InstrumentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.cnebrera.uc3.tech.lesson9.Instrument)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 instrumentId = 1;</code>
         */
        int getInstrumentId();

        /**
         * <code>optional string symbol = 2;</code>
         */
        java.lang.String getSymbol();
        /**
         * <code>optional string symbol = 2;</code>
         */
        com.google.protobuf.ByteString
        getSymbolBytes();
    }
    /**
     * Protobuf type {@code com.cnebrera.uc3.tech.lesson9.Instrument}
     */
    public  static final class Instrument extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.cnebrera.uc3.tech.lesson9.Instrument)
            InstrumentOrBuilder {
        // Use Instrument.newBuilder() to construct.
        private Instrument(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Instrument() {
            instrumentId_ = 0;
            symbol_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Instrument(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            instrumentId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            symbol_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder.class);
        }

        public static final int INSTRUMENTID_FIELD_NUMBER = 1;
        private int instrumentId_;
        /**
         * <code>optional int32 instrumentId = 1;</code>
         */
        public int getInstrumentId() {
            return instrumentId_;
        }

        public static final int SYMBOL_FIELD_NUMBER = 2;
        private volatile java.lang.Object symbol_;
        /**
         * <code>optional string symbol = 2;</code>
         */
        public java.lang.String getSymbol() {
            java.lang.Object ref = symbol_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                symbol_ = s;
                return s;
            }
        }
        /**
         * <code>optional string symbol = 2;</code>
         */
        public com.google.protobuf.ByteString
        getSymbolBytes() {
            java.lang.Object ref = symbol_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                symbol_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (instrumentId_ != 0) {
                output.writeInt32(1, instrumentId_);
            }
            if (!getSymbolBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (instrumentId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, instrumentId_);
            }
            if (!getSymbolBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument)) {
                return super.equals(obj);
            }
            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument other = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument) obj;

            boolean result = true;
            result = result && (getInstrumentId()
                    == other.getInstrumentId());
            result = result && getSymbol()
                    .equals(other.getSymbol());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + INSTRUMENTID_FIELD_NUMBER;
            hash = (53 * hash) + getInstrumentId();
            hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
            hash = (53 * hash) + getSymbol().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.cnebrera.uc3.tech.lesson9.Instrument}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.cnebrera.uc3.tech.lesson9.Instrument)
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder.class);
            }

            // Construct using com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                instrumentId_ = 0;

                symbol_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor;
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstanceForType() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance();
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument build() {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument buildPartial() {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument result = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument(this);
                result.instrumentId_ = instrumentId_;
                result.symbol_ = symbol_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument) {
                    return mergeFrom((com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument other) {
                if (other == com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance()) return this;
                if (other.getInstrumentId() != 0) {
                    setInstrumentId(other.getInstrumentId());
                }
                if (!other.getSymbol().isEmpty()) {
                    symbol_ = other.symbol_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int instrumentId_ ;
            /**
             * <code>optional int32 instrumentId = 1;</code>
             */
            public int getInstrumentId() {
                return instrumentId_;
            }
            /**
             * <code>optional int32 instrumentId = 1;</code>
             */
            public Builder setInstrumentId(int value) {

                instrumentId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 instrumentId = 1;</code>
             */
            public Builder clearInstrumentId() {

                instrumentId_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object symbol_ = "";
            /**
             * <code>optional string symbol = 2;</code>
             */
            public java.lang.String getSymbol() {
                java.lang.Object ref = symbol_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    symbol_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string symbol = 2;</code>
             */
            public com.google.protobuf.ByteString
            getSymbolBytes() {
                java.lang.Object ref = symbol_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    symbol_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string symbol = 2;</code>
             */
            public Builder setSymbol(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                symbol_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string symbol = 2;</code>
             */
            public Builder clearSymbol() {

                symbol_ = getDefaultInstance().getSymbol();
                onChanged();
                return this;
            }
            /**
             * <code>optional string symbol = 2;</code>
             */
            public Builder setSymbolBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                symbol_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.cnebrera.uc3.tech.lesson9.Instrument)
        }

        // @@protoc_insertion_point(class_scope:com.cnebrera.uc3.tech.lesson9.Instrument)
        private static final com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument();
        }

        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Instrument>
                PARSER = new com.google.protobuf.AbstractParser<Instrument>() {
            public Instrument parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Instrument(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Instrument> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Instrument> getParserForType() {
            return PARSER;
        }

        public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ReferenceDataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.cnebrera.uc3.tech.lesson9.ReferenceData)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 marketId = 1;</code>
         */
        int getMarketId();

        /**
         * <code>optional string algorithmIdentifier = 2;</code>
         */
        java.lang.String getAlgorithmIdentifier();
        /**
         * <code>optional string algorithmIdentifier = 2;</code>
         */
        com.google.protobuf.ByteString
        getAlgorithmIdentifierBytes();

        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument>
        getInstrumentList();
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index);
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        int getInstrumentCount();
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>
        getInstrumentOrBuilderList();
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code com.cnebrera.uc3.tech.lesson9.ReferenceData}
     */
    public  static final class ReferenceData extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.cnebrera.uc3.tech.lesson9.ReferenceData)
            ReferenceDataOrBuilder {
        // Use ReferenceData.newBuilder() to construct.
        private ReferenceData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private ReferenceData() {
            marketId_ = 0;
            algorithmIdentifier_ = "";
            instrument_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private ReferenceData(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            marketId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            algorithmIdentifier_ = s;
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                instrument_ = new java.util.ArrayList<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            instrument_.add(
                                    input.readMessage(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    instrument_ = java.util.Collections.unmodifiableList(instrument_);
                }
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.Builder.class);
        }

        private int bitField0_;
        public static final int MARKETID_FIELD_NUMBER = 1;
        private int marketId_;
        /**
         * <code>optional int32 marketId = 1;</code>
         */
        public int getMarketId() {
            return marketId_;
        }

        public static final int ALGORITHMIDENTIFIER_FIELD_NUMBER = 2;
        private volatile java.lang.Object algorithmIdentifier_;
        /**
         * <code>optional string algorithmIdentifier = 2;</code>
         */
        public java.lang.String getAlgorithmIdentifier() {
            java.lang.Object ref = algorithmIdentifier_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                algorithmIdentifier_ = s;
                return s;
            }
        }
        /**
         * <code>optional string algorithmIdentifier = 2;</code>
         */
        public com.google.protobuf.ByteString
        getAlgorithmIdentifierBytes() {
            java.lang.Object ref = algorithmIdentifier_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                algorithmIdentifier_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int INSTRUMENT_FIELD_NUMBER = 3;
        private java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> instrument_;
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> getInstrumentList() {
            return instrument_;
        }
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        public java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>
        getInstrumentOrBuilderList() {
            return instrument_;
        }
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        public int getInstrumentCount() {
            return instrument_.size();
        }
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index) {
            return instrument_.get(index);
        }
        /**
         * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
         */
        public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
                int index) {
            return instrument_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (marketId_ != 0) {
                output.writeInt32(1, marketId_);
            }
            if (!getAlgorithmIdentifierBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, algorithmIdentifier_);
            }
            for (int i = 0; i < instrument_.size(); i++) {
                output.writeMessage(3, instrument_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (marketId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, marketId_);
            }
            if (!getAlgorithmIdentifierBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, algorithmIdentifier_);
            }
            for (int i = 0; i < instrument_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, instrument_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData)) {
                return super.equals(obj);
            }
            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData other = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData) obj;

            boolean result = true;
            result = result && (getMarketId()
                    == other.getMarketId());
            result = result && getAlgorithmIdentifier()
                    .equals(other.getAlgorithmIdentifier());
            result = result && getInstrumentList()
                    .equals(other.getInstrumentList());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + MARKETID_FIELD_NUMBER;
            hash = (53 * hash) + getMarketId();
            hash = (37 * hash) + ALGORITHMIDENTIFIER_FIELD_NUMBER;
            hash = (53 * hash) + getAlgorithmIdentifier().hashCode();
            if (getInstrumentCount() > 0) {
                hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
                hash = (53 * hash) + getInstrumentList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.cnebrera.uc3.tech.lesson9.ReferenceData}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.cnebrera.uc3.tech.lesson9.ReferenceData)
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceDataOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.Builder.class);
            }

            // Construct using com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getInstrumentFieldBuilder();
                }
            }
            public Builder clear() {
                super.clear();
                marketId_ = 0;

                algorithmIdentifier_ = "";

                if (instrumentBuilder_ == null) {
                    instrument_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    instrumentBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor;
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstanceForType() {
                return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.getDefaultInstance();
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData build() {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData buildPartial() {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.marketId_ = marketId_;
                result.algorithmIdentifier_ = algorithmIdentifier_;
                if (instrumentBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        instrument_ = java.util.Collections.unmodifiableList(instrument_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.instrument_ = instrument_;
                } else {
                    result.instrument_ = instrumentBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData) {
                    return mergeFrom((com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData other) {
                if (other == com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.getDefaultInstance()) return this;
                if (other.getMarketId() != 0) {
                    setMarketId(other.getMarketId());
                }
                if (!other.getAlgorithmIdentifier().isEmpty()) {
                    algorithmIdentifier_ = other.algorithmIdentifier_;
                    onChanged();
                }
                if (instrumentBuilder_ == null) {
                    if (!other.instrument_.isEmpty()) {
                        if (instrument_.isEmpty()) {
                            instrument_ = other.instrument_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureInstrumentIsMutable();
                            instrument_.addAll(other.instrument_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.instrument_.isEmpty()) {
                        if (instrumentBuilder_.isEmpty()) {
                            instrumentBuilder_.dispose();
                            instrumentBuilder_ = null;
                            instrument_ = other.instrument_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            instrumentBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getInstrumentFieldBuilder() : null;
                        } else {
                            instrumentBuilder_.addAllMessages(other.instrument_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int marketId_ ;
            /**
             * <code>optional int32 marketId = 1;</code>
             */
            public int getMarketId() {
                return marketId_;
            }
            /**
             * <code>optional int32 marketId = 1;</code>
             */
            public Builder setMarketId(int value) {

                marketId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 marketId = 1;</code>
             */
            public Builder clearMarketId() {

                marketId_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object algorithmIdentifier_ = "";
            /**
             * <code>optional string algorithmIdentifier = 2;</code>
             */
            public java.lang.String getAlgorithmIdentifier() {
                java.lang.Object ref = algorithmIdentifier_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    algorithmIdentifier_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string algorithmIdentifier = 2;</code>
             */
            public com.google.protobuf.ByteString
            getAlgorithmIdentifierBytes() {
                java.lang.Object ref = algorithmIdentifier_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    algorithmIdentifier_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string algorithmIdentifier = 2;</code>
             */
            public Builder setAlgorithmIdentifier(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                algorithmIdentifier_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string algorithmIdentifier = 2;</code>
             */
            public Builder clearAlgorithmIdentifier() {

                algorithmIdentifier_ = getDefaultInstance().getAlgorithmIdentifier();
                onChanged();
                return this;
            }
            /**
             * <code>optional string algorithmIdentifier = 2;</code>
             */
            public Builder setAlgorithmIdentifierBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                algorithmIdentifier_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> instrument_ =
                    java.util.Collections.emptyList();
            private void ensureInstrumentIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    instrument_ = new java.util.ArrayList<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument>(instrument_);
                    bitField0_ |= 0x00000004;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> instrumentBuilder_;

            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> getInstrumentList() {
                if (instrumentBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(instrument_);
                } else {
                    return instrumentBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public int getInstrumentCount() {
                if (instrumentBuilder_ == null) {
                    return instrument_.size();
                } else {
                    return instrumentBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index) {
                if (instrumentBuilder_ == null) {
                    return instrument_.get(index);
                } else {
                    return instrumentBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder setInstrument(
                    int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
                if (instrumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureInstrumentIsMutable();
                    instrument_.set(index, value);
                    onChanged();
                } else {
                    instrumentBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder setInstrument(
                    int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
                if (instrumentBuilder_ == null) {
                    ensureInstrumentIsMutable();
                    instrument_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    instrumentBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder addInstrument(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
                if (instrumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureInstrumentIsMutable();
                    instrument_.add(value);
                    onChanged();
                } else {
                    instrumentBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder addInstrument(
                    int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
                if (instrumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureInstrumentIsMutable();
                    instrument_.add(index, value);
                    onChanged();
                } else {
                    instrumentBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder addInstrument(
                    com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
                if (instrumentBuilder_ == null) {
                    ensureInstrumentIsMutable();
                    instrument_.add(builderForValue.build());
                    onChanged();
                } else {
                    instrumentBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder addInstrument(
                    int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
                if (instrumentBuilder_ == null) {
                    ensureInstrumentIsMutable();
                    instrument_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    instrumentBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder addAllInstrument(
                    java.lang.Iterable<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> values) {
                if (instrumentBuilder_ == null) {
                    ensureInstrumentIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, instrument_);
                    onChanged();
                } else {
                    instrumentBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder clearInstrument() {
                if (instrumentBuilder_ == null) {
                    instrument_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    instrumentBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public Builder removeInstrument(int index) {
                if (instrumentBuilder_ == null) {
                    ensureInstrumentIsMutable();
                    instrument_.remove(index);
                    onChanged();
                } else {
                    instrumentBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder getInstrumentBuilder(
                    int index) {
                return getInstrumentFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
                    int index) {
                if (instrumentBuilder_ == null) {
                    return instrument_.get(index);  } else {
                    return instrumentBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>
            getInstrumentOrBuilderList() {
                if (instrumentBuilder_ != null) {
                    return instrumentBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(instrument_);
                }
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder addInstrumentBuilder() {
                return getInstrumentFieldBuilder().addBuilder(
                        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance());
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder addInstrumentBuilder(
                    int index) {
                return getInstrumentFieldBuilder().addBuilder(
                        index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance());
            }
            /**
             * <code>repeated .com.cnebrera.uc3.tech.lesson9.Instrument instrument = 3;</code>
             */
            public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder>
            getInstrumentBuilderList() {
                return getInstrumentFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>
            getInstrumentFieldBuilder() {
                if (instrumentBuilder_ == null) {
                    instrumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>(
                            instrument_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    instrument_ = null;
                }
                return instrumentBuilder_;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.cnebrera.uc3.tech.lesson9.ReferenceData)
        }

        // @@protoc_insertion_point(class_scope:com.cnebrera.uc3.tech.lesson9.ReferenceData)
        private static final com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData();
        }

        public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ReferenceData>
                PARSER = new com.google.protobuf.AbstractParser<ReferenceData>() {
            public ReferenceData parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ReferenceData(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ReferenceData> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ReferenceData> getParserForType() {
            return PARSER;
        }

        public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rlesson9.proto\022\035com.cnebrera.uc3.tech.l" +
                        "esson9\"2\n\nInstrument\022\024\n\014instrumentId\030\001 \001" +
                        "(\005\022\016\n\006symbol\030\002 \001(\t\"}\n\rReferenceData\022\020\n\010m" +
                        "arketId\030\001 \001(\005\022\033\n\023algorithmIdentifier\030\002 \001" +
                        "(\t\022=\n\ninstrument\030\003 \003(\0132).com.cnebrera.uc" +
                        "3.tech.lesson9.InstrumentB.\n#com.cnebrer" +
                        "a.uc3.tech.lesson9.protoB\007Lesson9b\006proto" +
                        "3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cnebrera_uc3_tech_lesson9_Instrument_descriptor,
                new java.lang.String[] { "InstrumentId", "Symbol", });
        internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cnebrera_uc3_tech_lesson9_ReferenceData_descriptor,
                new java.lang.String[] { "MarketId", "AlgorithmIdentifier", "Instrument", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
